# Generated by Django 4.2.3 on 2023-08-21 04:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_text_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='contents',
            field=models.TextField(default=datetime.datetime(2023, 8, 21, 4, 27, 52, 989599, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
