# Generated by Django 4.2.3 on 2023-08-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_contents_question_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='deadline',
            new_name='duedate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('warning', 'normal'), ('primary', 'low')], max_length=50, null=True),
        ),
    ]
