# Generated by Django 4.2.3 on 2023-08-22 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_deadline_question_duedate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='TodoModel',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
